apiVersion: v1
kind: Namespace
metadata:
  name: mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: mongodb
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: "mongodb/mongodb-enterprise-server:7.0-ubuntu2204"
          ports:
            - containerPort: 27017
          env:
            - name: MONGODB_BIND_IP
              value: "0.0.0.0"
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "mdbadmin"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "Passw0rd123!"
          volumeMounts:
            - name: data-volume
              mountPath: /data/db
      volumes:
        - name: data-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: mongodb
  labels:
    app: mongodb
spec:
  type: LoadBalancer
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongodb
