---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultPKISecret
metadata:
  namespace: vault
  name: vault-pki
spec:
  vaultAuthRef: example
  mount: pki_int
  role: example-dot-com
  commonName: "k8s.example.com"
  altNames: ["anothersan.example.com"]
  format: pem
  expiryOffset: 1s
  ttl: 60s
  destination:
    create: true
    name: vault-pki

