apiVersion: v1
kind: Pod
metadata:
  name: mypodpki
  namespace: vault
  # Using a different service account
spec:
  containers:
  - name: mypod
    image: redis
    volumeMounts:
    - name: foo
      mountPath: "/etc/foo"
      readOnly: true
  volumes:
  - name: foo
    secret:
      secretName: vault-pki
      optional: true
